---
- hosts: all
  become: yes

  tasks:
    - name: Make sure cache is updated if need be
      dnf: update_cache=true

    - name: Install qemu-guest-agent
      dnf: name=qemu-guest-agent state=present

    - name: Ensure qemu-guest-agent is running
      service: name=qemu-guest-agent state=started enabled=yes
