---
- name: Ansible Pull Scratch
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: Add GPG Key
      ansible.builtin.get_url:
        url: https://packages.adoptium.net/artifactory/api/gpg/key/public
        dest: /etc/apt/keyrings/adoptium.asc
        mode: '0755'

    - name: Add repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/adoptium.asc] https://packages.adoptium.net/artifactory/deb {{ ansible_distribution_release }} main"
        state: present
        update_cache: true

    - name: Install Java
      ansible.builtin.apt:
        name:
          - temurin-11-jdk

    - name: Install Unified Agent
      ansible.builtin.get_url:
        url: https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        dest: /home/ubuntu/wss-unified-agent.jar
        mode: '0444'
        checksum: sha256:https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar.sha256
