---
# Basic install docker engine
- name: Install Docker Engine on Linux Box
  hosts: all # or name, or {{ var }}
  become: yes

  tasks:
  - name: Update cache
    ansible.builtin.apt:
      update_cache: yes

  - name: CA Certs, curl, gnupg
    ansible.builtin.apt:
      name:
      - ca-certificates
      - curl
      - gnupg
      state: latest
      cache_valid_time: 3600  # update cache if more than an hour old. probably don't need it bc of step above

  - name: Add GPG Key
    ansible.builtin.get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: '0755'
        # force: true
      checksum: sha256:1500c1f56fa9e26b9b8f42452a553675796ade0807cdce11975eb98170b3a570

  - name: Add repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }}  stable"
      state: present
      update_cache: yes

  - name: Install Docker components
    ansible.builtin.apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      state: present
